#! /bin/sh

# $HOME/.config/polybar/launch.sh

bspc monitor HDMI-1 -n 0 -d 一 二 三 四
bspc monitor DVI-I-2 -n 1 -d 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
