#! /bin/sh

## home setup (using amdgpu)
export RIGHT_MONITOR=DisplayPort-0
export LEFT_MONITOR=HDMI-A-0

## Setup multi monitor configuration
xrandr \
    --output $LEFT_MONITOR --mode 2560x1440 --rate 59.95 \
    --output $RIGHT_MONITOR --mode 2560x1440 --rate 164.83 --right-of $LEFT_MONITOR

## Setup Polybar
# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# if type "xrandr"; then
#   for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
#     MONITOR=$m polybar --reload example &
#   done
# else
#   polybar --reload example &
# fi

# Launch Polybar, using default config location ~/.config/polybar/config
RIGHT_MONITOR=$RIGHT_MONITOR polybar right &
LEFT_MONITOR=$LEFT_MONITOR polybar left &
echo "Polybar launched..."

# $HOME/.config/polybar/launch.sh

# bspc monitor $LEFT_MONITOR -d 一 二 三 四 五 六 七 八 九 十
bspc monitor $LEFT_MONITOR -d 一 二 三 四 五
bspc monitor $RIGHT_MONITOR -d 六 七 八 九 十
## requires bspwm-rounded-corners from https://github.com/phuhl/bspwm-rounded
bspc config border_radius        8

bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^8'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
